spring:
  profiles:
    group:
      local:
        - oauth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test1234
  redis:
    port: 6379
    host: localhost
# client-id: 681375843184-2dka6lh5p5ngmar14l3trfemkskk63tn.apps.googleusercontent.com
# secret-key: 681375843184-2dka6lh5p5ngmar14l3trfemkskk63tn.apps.googleusercontent.com
# redirect-uri: http://localhost:8080
# grant-type: authorization_code
