spring:
  profiles:
    group:
      local:
        - oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 스웨거 설정, 안넣으면 시작에러남


  config:
    import: classpath:/application-aws.yml, classpath:/application-server.yml, classpath:/application-oauth.yml
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: foodiary-bucket
    stack:
      auto: false

  type-aliases-package: com.foodiary
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true


