spring:
  profiles:
    group:
      local:
        - oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foodiary_db
    username: mijuu
    password: vneldjfl124
  redis:
    port: 6379
    host: localhost

mybatis:
  type-aliases-package: com.foodiary
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
# client-id: 681375843184-2dka6lh5p5ngmar14l3trfemkskk63tn.apps.googleusercontent.com
# secret-key: 681375843184-2dka6lh5p5ngmar14l3trfemkskk63tn.apps.googleusercontent.com
# redirect-uri: http://localhost:8080
# grant-type: authorization_code

springdoc:
  # default-consumes-media-type: application/json
  # default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
