spring:
  profiles:
    group:
      local:
        - oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 스웨거 설정, 안넣으면 시작에러남

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 15MB

  config:
    import: classpath:/application-aws.yml, classpath:/application-oauth.yml, classpath:/application-server.yml, classpath:/application-smtp.yml
    

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: foodiary-bucket
    stack:
      auto: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true   

server:
  address: 127.0.0.1
  port: 8080