spring:
  profiles:
    group:
      local:
        - oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 스웨거 설정, 안넣으면 시작에러남

  redis:
    port: 6379
    host: localhost

  config:
    import: classpath:/application-aws.yml
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
      
#  # 미주 db
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/foodiary_db
#    username: mijuu
#    password: vneldjfl124

# 민택 db
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: test1234

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: foodiary-bucket
    stack:
      auto: false

jwt:
  secret-key: St5h23phd4V37SFvHXBY2Zwmfvkkgjecqib0Bxz5Eh2Ch4R5dz
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 360

mybatis:
  type-aliases-package: com.foodiary
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

google:
  client_id: 681375843184-2dka6lh5p5ngmar14l3trfemkskk63tn.apps.googleusercontent.com
  client_secret: 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
  redirect_uri: http://localhost:8080/oauth/google/callback
  grant_type: authorization_code
  scope: -profile
         -email
naver:
  client_id: 2wiUq3wF__ufyI6HMm06
  client_secret: O3n_qnR4iD
  redirect_uri: http://localhost:8080/oauth/naver/callback
  grant_type: authorization_code
  state : test
  scope: -profile
         -email