spring:
  # datasource:
  #   driver-class-name: sdfsdf
  #   url: sdfdsf
  #   username: sdfdf
  #   password: fdsdfs
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant_path_matcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  redis:
    port: 6379
    host: localhost

springdoc:
  # default-consumes-media-type: application/json
  # default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true