# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: foodiary-webapp

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Copy Secret
      env:
          FOODIARY_SECRET: ${{ secrets.FOODIARY_SECRET }}
          FOODIARY_SECRET_DIR: src/main/resources
          FOODIARY_SECRET_TEST_DIR: src/test/resources
          FOODIARY_SECRET_DIR_FILE_NAME: application-secret.yml
      run: echo $FOODIARY_SECRET | base64 --decode > $FOODIARY_SECRET_DIR/$FOODIARY_SECRET_DIR_FILE_NAME && 
           echo $FOODIARY_SECRET | base64 --decode > $FOODIARY_SECRET_TEST_DIR/$FOODIARY_SECRET_DIR_FILE_NAME
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew # gradle wrapper를 실행할 수 있도록 권한 부여
      shell: bash
      
    - name: Build with Gradle
      run: ./gradlew clean build # 프로젝트 빌드
      shell: bash
        
    - name: Get current time
      uses: 1466587594/get-current-time@v2  # 빌드 완료 시간 가져오기
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}" # 빌드 완료 시간 출력하기
      shell: bash
    
    # gradle build를 통해 만들어진 jar 파일 beanstalk에 배포하기 위한 zip 파일로 만듬
    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cd deploy && zip -r deploy.zip .
      
    - name: Beanstalk Deploy
    # You may pin to the exact commit or the version.
    # uses: einaregilsson/beanstalk-deploy@18e5b85bd914cabf00fccabe72f60b8757dcd3cb
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        # AWS Access Key
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        # AWS Secret Key
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Region
        region: ap-northeast-2
        # Beanstalk application name
        application_name: foodiary
        # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
        environment_name: Foodiary-env
        # Version label for new Beanstalk version
        version_label: github-action-${{steps.current-time.outputs.formattedTime}}
        # Version description for the new Beanstalk version
        deployment_package: deploy/deploy.zip
        # Whether the action should skip creating a new bucket and use the given one to upload the deployment package to instead. When omitted the actions will (try to) create a new one during deployment.
