name: foodiary-webapp 

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./foodiary

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: make application-secret.yml
      run: |
        cd foodiary
        cd src/main/resources
        touch ./application-secret.yml
        echo $FOODIARY_SECRET | base64 --decode >> ./application-secret.yml
      shell: bash
      env:
          FOODIARY_SECRET: ${{ secrets.FOODIARY_SECRET }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # gradle wrapper를 실행할 수 있도록 권한 부여
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew clean build # 프로젝트 빌드
      working-directory: ${{ env.working-directory }}
        
    - name: Get current time
      uses: 1466587594/get-current-time@v2  # 빌드 완료 시간 가져오기
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}" # 빌드 완료 시간 출력하기
      working-directory: ${{ env.working-directory }}
      shell: bash
    
    # gradle build를 통해 만들어진 jar 파일 beanstalk에 배포하기 위한 zip 파일로 만듬
    - name: Generate deployment package
      run: |
        cd foodiary
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cd deploy && zip -r deploy.zip .
      
    - name: Beanstalk Deploy
    # You may pin to the exact commit or the version.
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        # AWS Access Key
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        # AWS Secret Key
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Region
        region: ap-northeast-2
        # Beanstalk application name
        application_name: foodiary
        # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
        environment_name: Foodiary-env
        # Version label for new Beanstalk version
        version_label: github-action-${{steps.current-time.outputs.formattedTime}}
        # Version description for the new Beanstalk version
        deployment_package: foodiary/deploy/deploy.zip 
